Many fullstack-one modules migrated into soniq structure + website added (#131)
* Migration PoC 3

* Remove orm examples since they will not work anymore

* Update example

* Remove build from example

* Ignore example build

* UpdatedAt Trigger working

* gql config in db and auto-reload of ApolloServer at the moment with every request

* Move Auth-Config to PG and make it updatable without reboot

* Clean up auth config, update cookie settings without reboot, cache perperation

* Fix server config and clean up

* Remove deprecated packages: schema-builder, db, helper, boot-loader, boot-scripts

* FileStorage running

* Computed column support

* JSON Schema export for columnExtensions and convert fileStorage trigger from plv8 to plpgsql

* Option to move select of generic and computed columns to query-builder instead of the view for performance improvements

* TS Model Test files

* Model GUI for Schema creation

* Adjust example

* Changed packages

* Work on root gql queries to pass a sqlClient

* Add dotenv file for example to see logs in demos

* Working Version with simplified JSON-Schema - Delete-Mutation not working

* Working Version with simplified JSON-Schema - Delete-Mutation not working - 2

* envfile

* Added more packages from v1/mig3

* Set min Node-js version to 12 in nvmrc

* Refactoring ongoing

* Add rush add command to docs

* Add useRootViews for context and contextPgClient for SQL + GQL Transactions

* Git hook: update prettier path

* EsLint: Create shared config module

* EsLint: Create shared config module

* Add Graphql, Auth and Update Server Modules

* Update packages to merge

* Fix shrinkwrap.yaml file

* Migrate gql and auth to rush  :tada:

* Add prettify to git hook

* Add colors to pre-commit hook

* test commit

* Fix ts-ignore todos

* Added types, interfaces and removed some anys and ts-ignores from Auth and Graphql package

* Refactor Auth, Server, GraphQl and Core to build config with generator classes and create interfaces for everything

* Add typedef for pg

* Update tslog to 2.0.0

* Update examples

* Add min node engine 12 and activate npm strict mode

* Add website based on docsify

Co-authored-by: dustin-H

diff --git a/common/git-hooks/pre-commit b/common/git-hooks/pre-commit
--- a/common/git-hooks/pre-commit
+++ b/common/git-hooks/pre-commit
@@ -6,20 +6,24 @@ echo Starting Git hook: pre-commit
 FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
+echo "Prettify..."
+
 # Prettify all selected files
-echo "$FILES" | xargs ./node_modules/.bin/prettier --write
+echo "$FILES" | xargs ./common/temp/node_modules/.bin/prettier --write --config ./modules/eslint-config/prettier.config.js
+
+echo "ESLint..."
 
 # ESLint
-echo "$FILES" | xargs ./common/temp/node_modules/.bin/eslint --ext .ts --ignore-pattern tests/*
+echo "$FILES" | xargs ./common/temp/node_modules/.bin/eslint --ext .ts --ignore-pattern 'tests/*' --ignore-pattern '_v1/*'  --ignore-pattern '_v1_mig3/*'
 eslint_exit=$?
 
 # Add back the modified/prettified files to staging
 echo "$FILES" | xargs git add
 
 if [ ${eslint_exit} -eq 0 ]; then
-  echo "✓ ESLint passed"
+  echo "\x1b[32m ✓ ESLint passed"
 else
-  echo "✘ ESLint failed!" 1>&2
+  echo "\x1b[31m ✘ ESLint failed!" 1>&2
   exit ${eslint_exit}
 fi
 
